spring:
  cloud:
    consul:
      discovery:
        enabled: true
        health-check-interval: 10s
        health-check-url: http://127.0.0.1:${server.port}/actuator/health
        instance-id: ${spring.application.name}:127.0.0.1:${server.port}
        port: ${server.port}
        service-name: ${spring.application.name}
        tags: dev
      enabled: true
      host: 127.0.0.1
      port: 8500

  datasource:
    url: jdbc:mysql://47.101.42.169:3306/db_eagleeye_auth?characterEncoding=utf8&useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    username: berry
    password: okmnji123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql

  redis:
    database: 7
    host: 47.101.42.169
    port: 6379
    password: okmnji123
    timeout: 5000ms
  session:
    store-type: none

uaa:
  key-store:
    name: keystore.jks
    password: berry123
    alias: keystore